### ISSUE TITLE
Being pushed back with Google's new filters

### ISSUE THREAD

**Issue by NoahBK** [marioortizmanero/reddit-search-on-google#9]
The userscript still works, but it is being pushed back to other pages (as in having to be on images to even see it now i.e. [here](https://i.imgur.com/FqfDJl5.png)) On top of that, is it possible to fix this issue by removing the other un-needed filter icons such as News, Shopping, Books, Maps, Flights, ETC? I looked around a bit to find an answer for this before making an issue here, but found no other people talking about it or a way to fix it. 

It doesn't even show up on main searches now because of all the new filters I talked about above. [Example here](https://i.imgur.com/GZVm7Xn.png)

**EDIT**: There is another post on [Greasyfork](https://greasyfork.org/en/scripts/381497-reddit-search-on-google/discussions/152738) about the same issue.

**Comment by tadwohlrapp** [comment]
@NoahBK Which browser and device are you on? I've never seen that specific UI on Google search.

**Comment by NoahBK** [comment]
@tadwohlrapp I am using Brave browser on version 1.46.144. This UI has since seemingly changed and this userscript is now working again, but at the time of writing this comment it was definitely a little messed up for some reason.

**Comment by heubergen** [comment]
I got the new design today and fixed the main issue in a patch:
https://github.com/marioortizmanero/reddit-search-on-google/pull/10

As mentioned, it only supports the main search (not image) and not with any non-default settings. Feel free to copy it and close the PR without merging it.
